### ISSUE TITLE
wagtail 2.4 with codered 13.3 issue

### ISSUE THREAD

**Issue by auvipy** [coderedcorp/coderedcms#167]
Event Label', max_length=255, required=False))])), ('page_link', wagtail.core.blocks.PageChooserBlock(label='Page link', required=False)), ('doc_link', wagtail.documents.blocks.DocumentChooserBlock(label='Document link', required=False)), ('other_link', wagtail.core.blocks.CharBlock(label='Other link', max_length=255, required=False)), ('button_title', wagtail.core.blocks.CharBlock(label='Button Title', max_length=255, required=True)), ('button_style', wagtail.core.blocks.ChoiceBlock(choices=[('btn-primary', 'Primary'), ('btn-secondary', 'Secondary'), ('btn-success', 'Success'), ('btn-danger', 'Danger'), ('btn-warning', 'Warning'), ('btn-info', 'Info'), ('btn-link', 'Link'), ('btn-light', 'Light'), ('btn-dark', 'Dark'), ('btn-outline-primary', 'Outline Primary'), ('btn-outline-secondary', 'Outline Secondary'), ('btn-success', 'Outline Success'), ('btn-outline-danger', 'Outline Danger'), ('btn-outline-warning', 'Outline Warning'), ('btn-outline-info', 'Outline Info'), ('btn-outline-light', 'Outline Light'), ('btn-outline-dark', 'Outline Dark')], label='Button Style', required=False)), ('button_size', wagtail.core.blocks.ChoiceBlock(choices=[('btn-sm', 'Small'), ('', 'Default'), ('btn-lg', 'Large')], label='Button Size', required=False))]))], blank=True, label='Links', required=False))]))], label='Content'))])), ('html', wagtail.core.blocks.RawHTMLBlock(classname='monospace', icon='code', label='HTML'))], blank=True, null=True),
AttributeError: module 'coderedcms.blocks.html_blocks' has no attribute 'RichTextBlock'

**Comment by vsalvino** [comment]
Hi @auvipy - this is due to a change in 0.14. in 0.14, our RichTextBlock is in `coderedcms.blocks.html_blocks`. Pior to 0.14, RichTextBlock was in `coderedcms.blocks.content_blocks`.

After upgrading to 0.14 you should update your old migrations as so:
Replace:
```python
coderedcms.blocks.content_blocks.RichTextBlock
```
with
```python
coderedcms.blocks.html_blocks.RichTextBlock
```

When referencing any of our blocks in your own code, you should just import as: `from coderedcms.blocks import <block>`

Let me know if you are able to get it resolved.

**Comment by auvipy** [comment]
its fixed in the newer release thanks
